rd  /S /Q ".vs\GRT-MXLoader\v17\ipch"
del /S /Q ".vs\GRT-MXLoader\v17\Browse.VC.db"
del /S /Q ".vs\GRT-MXLoader\v17\Solution.VC.db"

rd /S /Q "Debug"
rd /S /Q "Release"
rd /S /Q "x64"
rd /S /Q "x86"

rd /S /Q "builder\cs-beacon\Debug"
rd /S /Q "builder\cs-beacon\Release"
rd /S /Q "builder\cs-beacon\x64"
rd /S /Q "builder\cs-beacon\x86"
rd /S /Q "builder\dotnet\Debug"
rd /S /Q "builder\dotnet\Release"
rd /S /Q "builder\dotnet\x64"
rd /S /Q "builder\dotnet\x86"

rd /S /Q "payload\cs-beacon\Debug"
rd /S /Q "payload\cs-beacon\Release"
rd /S /Q "payload\cs-beacon\x64"
rd /S /Q "payload\cs-beacon\x86"
rd /S /Q "payload\dotnet_exe\bin"
rd /S /Q "payload\dotnet_exe\obj"
rd /S /Q "payload\dotnet_dll\bin"
rd /S /Q "payload\dotnet_dll\obj"

rd /S /Q "test\cs-beacon\Debug"
rd /S /Q "test\cs-beacon\Release"
rd /S /Q "test\cs-beacon\x64"
rd /S /Q "test\cs-beacon\x86"
rd /S /Q "test\dotnet\Debug"
rd /S /Q "test\dotnet\Release"
rd /S /Q "test\dotnet\x64"
rd /S /Q "test\dotnet\x86"
